// Copyright 2026 David Monagle / Monagle Pty Ltd
// SPDX-License-Identifier: MIT
//
// protoc-gen-connect-swift-server: a protoc plugin that emits Swift bindings
// for registering services on a `ConnectRouter` from `ConnectServer`.
//
// Output: for each `.proto` file containing services, a `<file>.connect.swift`
// containing one struct per service. The user constructs the struct with one
// closure per RPC method and calls `register(with:&router)`.
//
// Usage:
//   protoc --connect-swift-server_out=. helloworld.proto
//   buf generate                        # if configured in buf.gen.yaml

import Foundation
import SwiftProtobuf
import SwiftProtobufPluginLibrary

// MARK: - Plugin entry point

@main
struct ConnectSwiftServerGenerator: CodeGenerator {
    var version: String? { "0.1.0" }
    var projectURL: String? { "https://github.com/monagle-au/connect-swift-server" }
    var supportedFeatures: [Google_Protobuf_Compiler_CodeGeneratorResponse.Feature] = [.proto3Optional]

    func generate(
        files: [SwiftProtobufPluginLibrary.FileDescriptor],
        parameter: any CodeGeneratorParameter,
        protoCompilerContext: any ProtoCompilerContext,
        generatorOutputs: any GeneratorOutputs
    ) throws {
        let mappings = ProtoFileToModuleMappings()
        for file in files {
            guard !file.services.isEmpty else { continue }
            let namer = SwiftProtobufNamer(currentFile: file, protoFileToModuleMappings: mappings)
            let outputName = outputFilename(for: file.name)
            let content = ServiceCodeGenerator.generate(file: file, namer: namer)
            try generatorOutputs.add(fileName: outputName, contents: content)
        }
    }

    /// "foo/bar/baz.proto" → "foo/bar/baz.connect.swift"
    private func outputFilename(for protoName: String) -> String {
        var name = protoName
        if name.hasSuffix(".proto") { name.removeLast(".proto".count) }
        return name + ".connect.swift"
    }
}

// MARK: - Code generation

enum ServiceCodeGenerator {
    static func generate(
        file: SwiftProtobufPluginLibrary.FileDescriptor,
        namer: SwiftProtobufNamer
    ) -> String {
        var out = """
            // DO NOT EDIT.
            //
            // Generated by protoc-gen-connect-swift-server.
            // Source: \(file.name)

            import ConnectServer
            import GRPCCore
            import SwiftProtobuf


            """
        for service in file.services {
            emitService(service, namer: namer, into: &out)
            out += "\n"
        }
        return out
    }

    // MARK: - Per-service emission

    private static func emitService(
        _ service: ServiceDescriptor,
        namer: SwiftProtobufNamer,
        into out: inout String
    ) {
        let typeName = swiftServiceTypeName(service)
        let serviceFQN = service.fullName  // proto: e.g. "helloworld.Greeter"

        // Generate one initializer parameter and stored closure per method.
        out += "/// Connect-server bindings for service `\(serviceFQN)`.\n"
        out += "///\n"
        out += "/// Construct with one closure per RPC method, then call `register(with:&router)`.\n"
        out += "public struct \(typeName): Sendable {\n"

        // Stored closures
        for method in service.methods {
            out += "    public let \(methodPropertyName(method)): \(methodClosureType(method, namer: namer))\n"
        }

        // Initializer
        out += "\n    public init(\n"
        let initParams = service.methods.enumerated().map { (idx, method) -> String in
            let name = methodPropertyName(method)
            let type = methodClosureType(method, namer: namer)
            let comma = idx == service.methods.count - 1 ? "" : ","
            return "        \(name): @escaping \(type)\(comma)"
        }
        out += initParams.joined(separator: "\n")
        out += "\n    ) {\n"
        for method in service.methods {
            let name = methodPropertyName(method)
            out += "        self.\(name) = \(name)\n"
        }
        out += "    }\n\n"

        // register(with:&router)
        out += "    /// Registers all RPC methods on the given `ConnectRouter`.\n"
        out += "    public func register(with router: inout ConnectRouter) {\n"
        for method in service.methods {
            emitRegisterCall(method, serviceFQN: serviceFQN, namer: namer, into: &out)
        }
        out += "    }\n"
        out += "}\n"
    }

    // MARK: - Per-method emission

    private static func emitRegisterCall(
        _ method: MethodDescriptor,
        serviceFQN: String,
        namer: SwiftProtobufNamer,
        into out: inout String
    ) {
        let inputType = namer.fullName(message: method.inputType)
        let outputType = namer.fullName(message: method.outputType)
        let methodName = method.name
        let prop = methodPropertyName(method)

        let registerFn: String
        switch (method.clientStreaming, method.serverStreaming) {
        case (false, false): registerFn = "registerUnary"
        case (false, true):  registerFn = "registerServerStreaming"
        case (true, false):  registerFn = "registerClientStreaming"
        case (true, true):   registerFn = "registerBidirectional"
        }

        out += "        router.\(registerFn)(\n"
        out += "            method: MethodDescriptor(fullyQualifiedService: \"\(serviceFQN)\", method: \"\(methodName)\"),\n"
        out += "            requestType: \(inputType).self,\n"
        out += "            responseType: \(outputType).self,\n"
        out += "            handler: self.\(prop)\n"
        out += "        )\n"
    }

    // MARK: - Naming helpers

    /// Service "helloworld.Greeter" → "Helloworld_GreeterConnectService"
    private static func swiftServiceTypeName(_ service: ServiceDescriptor) -> String {
        // We construct: <typePrefix><ServiceName>ConnectService
        // typePrefix uses the swift_prefix file option / package convention.
        let parts = service.fullName.split(separator: ".")
        let pkgParts = parts.dropLast()
        let serviceName = parts.last.map(String.init) ?? service.name
        let prefix = pkgParts.map { $0.capitalizedFirst }.joined(separator: "_")
        if prefix.isEmpty {
            return "\(serviceName)ConnectService"
        } else {
            return "\(prefix)_\(serviceName)ConnectService"
        }
    }

    /// "SayHello" → "sayHello"
    private static func methodPropertyName(_ method: MethodDescriptor) -> String {
        let n = method.name
        guard let first = n.first else { return n }
        return String(first.lowercased()) + n.dropFirst()
    }

    /// Closure type for a method, matching ConnectRouter.register* handler signatures.
    private static func methodClosureType(_ method: MethodDescriptor, namer: SwiftProtobufNamer) -> String {
        let inputType = namer.fullName(message: method.inputType)
        let outputType = namer.fullName(message: method.outputType)
        switch (method.clientStreaming, method.serverStreaming) {
        case (false, false):
            // Unary: (Input, ServerContext) async throws -> Output
            return "@Sendable (\(inputType), ServerContext) async throws -> \(outputType)"
        case (false, true):
            // Server-streaming: (Input, ServerContext, ServerStreamWriter<Output>) async throws -> Void
            return "@Sendable (\(inputType), ServerContext, ServerStreamWriter<\(outputType)>) async throws -> Void"
        case (true, false):
            // Client-streaming: (AsyncThrowingStream<Input, any Error>, ServerContext) async throws -> Output
            return "@Sendable (AsyncThrowingStream<\(inputType), any Error>, ServerContext) async throws -> \(outputType)"
        case (true, true):
            // Bidi: (AsyncThrowingStream<Input, any Error>, ServerContext, ServerStreamWriter<Output>) async throws -> Void
            return "@Sendable (AsyncThrowingStream<\(inputType), any Error>, ServerContext, ServerStreamWriter<\(outputType)>) async throws -> Void"
        }
    }
}

// MARK: - Helpers

extension Substring {
    fileprivate var capitalizedFirst: String {
        guard let first = self.first else { return String(self) }
        return String(first.uppercased()) + self.dropFirst()
    }
}
